#!/usr/bin/env bash
#
# One-shot server deploy for Alpha POS + the POS Control Center, behind a Caddy
# reverse proxy with automatic HTTPS via nip.io (no domain needed).
#
#   ./deploy.sh <SERVER_PUBLIC_IP>
#
# Assumes (Linux + Docker already installed):
#   - this script lives in the alpha_pos repo:   ~/alpha_pos/deploy/deploy.sh
#   - the control center repo is cloned next to it: ~/pos_control
#     (override with CONTROL_DIR=/path ./deploy.sh <ip>)
#
# It is idempotent: re-running regenerates the Caddyfile/overrides and brings
# the stacks back up. Secrets in an existing .env are PRESERVED (never rotated
# out from under a running DB).
set -euo pipefail

IP="${1:?Usage: ./deploy.sh <SERVER_PUBLIC_IP>}"
ALPHA_DIR="${ALPHA_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
CONTROL_DIR="${CONTROL_DIR:-$(dirname "$ALPHA_DIR")/pos_control}"
DEPLOY_DIR="$ALPHA_DIR/deploy"

POS_HOST="pos.${IP}.nip.io"
CONTROL_HOST="control.${IP}.nip.io"

echo ">> alpha_pos : $ALPHA_DIR"
echo ">> control   : $CONTROL_DIR"
echo ">> POS URL   : https://${POS_HOST}"
echo ">> CTRL URL  : https://${CONTROL_HOST}"
[ -d "$CONTROL_DIR" ] || { echo "ERROR: control center repo not found at $CONTROL_DIR (set CONTROL_DIR=...)"; exit 1; }

# --- helpers ---------------------------------------------------------------
rand()   { head -c "${1:-48}" /dev/urandom | base64 | tr -d '\n' | tr '+/' '-_' | tr -d '='; }
fernet() { head -c 32 /dev/urandom | base64 | tr '+/' '-_'; }  # 32-byte urlsafe b64 = Fernet key

# Read an existing KEY=value from a .env (so secrets persist across re-runs).
keep() { local f="$1" k="$2"; [ -f "$f" ] && sed -n "s/^${k}=//p" "$f" | head -n1 || true; }

# --- 1. shared edge network ------------------------------------------------
docker network inspect edge >/dev/null 2>&1 || docker network create edge
echo ">> edge network ready"

# --- 2. alpha_pos .env -----------------------------------------------------
A_ENV="$ALPHA_DIR/.env"
A_SECRET="$(keep "$A_ENV" SECRET_KEY)";   A_SECRET="${A_SECRET:-$(rand 64)}"
A_DBPASS="$(keep "$A_ENV" DB_PASSWORD)";  A_DBPASS="${A_DBPASS:-$(rand 32)}"
A_FERNET="$(keep "$A_ENV" LICENSE_FERNET_KEY)"; A_FERNET="${A_FERNET:-$(fernet)}"
A_SYNCMGMT="$(keep "$A_ENV" SYNC_MANAGEMENT_TOKEN)"; A_SYNCMGMT="${A_SYNCMGMT:-$(rand 32)}"
A_CLOUDTOK="$(keep "$A_ENV" CLOUD_SYNC_TOKEN)"; A_CLOUDTOK="${A_CLOUDTOK:-$(rand 32)}"
cat > "$A_ENV" <<EOF
# Generated by deploy/deploy.sh — Alpha POS cloud backend
DEBUG=False
SECRET_KEY=${A_SECRET}
ALLOWED_HOSTS=${POS_HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${POS_HOST}
WEB_PORT=127.0.0.1:8001

DB_ENGINE=django.db.backends.postgresql
DB_NAME=alpha_pos
DB_USER=alpha_pos
DB_PASSWORD=${A_DBPASS}
DB_HOST=db
DB_PORT=5432

USE_REDIS=True
REDIS_URL=redis://redis:6379/0

# Behind Caddy (TLS terminated at the proxy)
TRUST_FORWARDED_PROTO=True
TRUST_FORWARDED_FOR=True

# Licensing: this is vendor infra, licensed offline (no control-center call,
# which also avoids the https-required check). Heartbeat daemon off.
LICENSE_FERNET_KEY=${A_FERNET}
LICENSE_HEARTBEAT_DISABLED=1

# Sync: this server RECEIVES branch data.
SYNC_ENABLED=True
SYNC_MANAGEMENT_TOKEN=${A_SYNCMGMT}
CLOUD_SYNC_TOKEN=${A_CLOUDTOK}
EOF
echo ">> wrote $A_ENV"

# --- 3. pos_control .env ---------------------------------------------------
C_ENV="$CONTROL_DIR/.env"
C_SECRET="$(keep "$C_ENV" SECRET_KEY)";  C_SECRET="${C_SECRET:-$(rand 64)}"
C_DBPASS="$(keep "$C_ENV" DB_PASSWORD)"; C_DBPASS="${C_DBPASS:-$(rand 32)}"
cat > "$C_ENV" <<EOF
# Generated by deploy/deploy.sh — POS Control Center
DEBUG=False
SECRET_KEY=${C_SECRET}
ALLOWED_HOSTS=${CONTROL_HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${CONTROL_HOST}
WEB_PORT=127.0.0.1:8002

DB_ENGINE=django.db.backends.postgresql
DB_NAME=pos_control_center
DB_USER=pos_control_center
DB_PASSWORD=${C_DBPASS}
DB_HOST=db
DB_PORT=5432

TRUST_FORWARDED_PROTO=True
EOF
echo ">> wrote $C_ENV"

# --- 4. edge-network compose overrides (attach web, give a stable alias) ---
cat > "$ALPHA_DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [alpha-web]
networks:
  edge:
    external: true
EOF
cat > "$CONTROL_DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [control-web]
networks:
  edge:
    external: true
EOF
echo ">> wrote edge overrides"

# --- 5. Caddy reverse proxy (auto-HTTPS via Let's Encrypt over nip.io) ------
mkdir -p "$DEPLOY_DIR/caddy"
cat > "$DEPLOY_DIR/caddy/Caddyfile" <<EOF
${POS_HOST} {
	reverse_proxy alpha-web:8000
}

${CONTROL_HOST} {
	reverse_proxy control-web:8000
}
EOF
echo ">> wrote Caddyfile"

# --- 6. bring the stacks up ------------------------------------------------
echo ">> building + starting alpha_pos ..."
( cd "$ALPHA_DIR" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )

echo ">> building + starting pos_control ..."
( cd "$CONTROL_DIR" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )

echo ">> starting caddy ..."
( cd "$DEPLOY_DIR/caddy" && docker compose up -d )

cat <<EOF

============================================================
  Stacks are up. Finish with these one-time steps:
============================================================

# 1) Alpha POS cloud — license it offline (clears the kill switch) + make admin:
cd "$ALPHA_DIR"
docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec -T web \\
    python manage.py activate_offline --email vendor@local --org "AlphaPOS Cloud" --perpetual
docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec -T web \\
    python manage.py bootstrap_admin --email admin@alpha.local --password 'CHANGE-ME-strong'

# 2) Control center — create the dashboard superuser (interactive prompt):
cd "$CONTROL_DIR"
docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec web \\
    python manage.py createsuperuser

# 3) Verify (give Caddy ~30s to issue certs on first run):
curl -fsS  https://${POS_HOST}/healthz   && echo "  POS OK"
curl -fsSI https://${CONTROL_HOST}/      | head -1

Cloud POS admin : https://${POS_HOST}/admin/
Control center  : https://${CONTROL_HOST}/
Sync push token (CLOUD_SYNC_TOKEN) for desktops: ${A_CLOUDTOK}
============================================================
EOF
