"""Local config + secret management for the desktop app.

Everything the operator enters lives in BASE_DIR/.env (the same env vars
settings.py reads). Secrets (SECRET_KEY, license Fernet key) are generated once
and persisted next to the project, mirroring run.py so a desktop launch and a
`python run.py` launch share state. Desktop-only flags (ToS acceptance) live in
config.json.

NOTE: .env holds this ONE business's own fiscal credentials. It is never shared
between installs.
"""
from __future__ import annotations

import json
import os
import secrets
import sys
from pathlib import Path


def _data_dir() -> Path:
    """Persistent, writable data dir. In a packaged build BASE_DIR is a temp
    extraction dir wiped each launch, so we store DB/secrets/config under
    %LOCALAPPDATA%\\AlphaPOS instead. From source, use the project root."""
    if getattr(sys, 'frozen', False):
        base = os.environ.get('LOCALAPPDATA') or str(Path.home())
        return Path(base) / 'AlphaPOS'
    return Path(__file__).resolve().parent.parent


DATA_DIR = _data_dir()
DATA_DIR.mkdir(parents=True, exist_ok=True)
ENV_FILE = DATA_DIR / '.env'
SECRET_FILE = DATA_DIR / '.secret_key'
FERNET_FILE = DATA_DIR / '.license_fernet_key'
STATE_FILE = DATA_DIR / 'desktop_state.json'

# The fields the control-panel config form manages, with sensible defaults.
# Grouped only for the UI; stored flat in .env.
CONFIG_FIELDS = [
    # General
    ('BRANCH_ID', 'main'),
    ('DEPLOYMENT_MODE', 'local'),
    ('PORT', '8000'),
    # Licensing / control center
    ('LICENSE_CONTROL_CENTER_URL', ''),
    # Sync (cloud)
    ('SYNC_ENABLED', 'False'),
    ('CLOUD_SYNC_URL', ''),
    ('CLOUD_SYNC_TOKEN', ''),
    # Telegram
    ('TELEGRAM_BOT_TOKEN', ''),
    ('TELEGRAM_WEBHOOK_SECRET', ''),
    # Fiscalization (this business's OWN identity)
    ('FISCALIZATION_MODE', 'off'),
    ('FISCAL_PROVIDER', 'mock'),
    ('FISCAL_TIN', ''),
    ('FISCAL_PROVIDER_URL', ''),
    ('FISCAL_MERCHANT_ID', ''),
    ('FISCAL_SECRET', ''),
    ('FISCAL_VAT_PERCENT', '0'),
    ('FISCAL_BLOCK_ON_FAILURE', 'false'),
]

SECRET_KEYS = {'FISCAL_SECRET', 'CLOUD_SYNC_TOKEN', 'TELEGRAM_BOT_TOKEN',
               'TELEGRAM_WEBHOOK_SECRET'}


def _write_protected(path: Path, contents: str) -> None:
    path.write_text(contents, encoding='utf-8')
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def load_or_generate_secret() -> str:
    if SECRET_FILE.exists():
        return SECRET_FILE.read_text(encoding='utf-8').strip()
    key = secrets.token_urlsafe(64)
    _write_protected(SECRET_FILE, key + '\n')
    return key


def load_or_generate_fernet() -> str:
    if FERNET_FILE.exists():
        return FERNET_FILE.read_text(encoding='utf-8').strip()
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode('ascii')
    _write_protected(FERNET_FILE, key + '\n')
    return key


def parse_env_file() -> dict:
    data = {}
    if not ENV_FILE.exists():
        return data
    for line in ENV_FILE.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, _, v = line.partition('=')
        data[k.strip()] = v.strip()
    return data


def read_config() -> dict:
    """Current config values for the form (existing .env merged over defaults)."""
    env = parse_env_file()
    return {k: env.get(k, default) for k, default in CONFIG_FIELDS}


def write_config(values: dict) -> None:
    """Persist the form values into .env, preserving any unmanaged keys."""
    existing = parse_env_file()
    for k, default in CONFIG_FIELDS:
        if k in values and values[k] is not None:
            existing[k] = str(values[k])
        else:
            existing.setdefault(k, default)
    lines = ['# Alpha POS configuration — generated by the desktop control panel',
             '# This file holds THIS business\'s own settings + fiscal identity.', '']
    for k in sorted(existing):
        lines.append(f'{k}={existing[k]}')
    _write_protected(ENV_FILE, '\n'.join(lines) + '\n')


def apply_env_to_process() -> None:
    """Load .env + the generated secrets into os.environ. MUST run before
    django.setup() so settings.py sees them."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'alpha_pos.settings')
    # Tell settings.py where to keep the DB / logs / media (persistent).
    os.environ.setdefault('ALPHA_POS_DATA_DIR', str(DATA_DIR))
    os.environ.setdefault('SECRET_KEY', load_or_generate_secret())
    os.environ.setdefault('LICENSE_FERNET_KEY', load_or_generate_fernet())
    os.environ.setdefault('DEBUG', 'False')
    os.environ.setdefault('ALLOWED_HOSTS', 'localhost,127.0.0.1')
    for k, v in parse_env_file().items():
        os.environ[k] = v


def read_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text(encoding='utf-8'))
        except (ValueError, OSError):
            return {}
    return {}


def write_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding='utf-8')


def tos_accepted() -> bool:
    return bool(read_state().get('tos_accepted'))


def accept_tos() -> None:
    state = read_state()
    state['tos_accepted'] = True
    write_state(state)
